repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: tests/repositories/fixtures/pypi.org/metadata/.*\.metadata
      - id: end-of-file-fixer
        exclude: ^.*\.egg-info/|tests/repositories/fixtures/pypi.org/metadata/.*\.metadata
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-toml
        exclude: tests/fixtures/invalid_lock/poetry\.lock
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.3.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [ --fix, --config=./pyproject.toml ]
      - id: ruff-format
        args: [ --config=./pyproject.toml ]

  - repo: https://github.com/hauntsaninja/no_implicit_optional
    rev: '1.4'
    hooks:
    -   id: no_implicit_optional
        name: no_implicit_optional
        description: "A codemod to make your implicit optional type hints PEP 484 compliant"
        entry: no_implicit_optional
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.16
    hooks:
      - id: uv-lock
